// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbwwmidlkithmatjyhog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZid3dtaWRsa2l0aG1hdGp5aG9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTQ2NzIsImV4cCI6MjA3MDEzMDY3Mn0.aiOuR_6svBIbnE2x98uis5D6BdXb358Z2S2HrRlO0PM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});